### PR TITLE
Support Laravel 5.2.

### PR DESCRIPTION
**Pull request by furey**

### CODE REVIEW

**Comment by ooxif** [comment]
thx!

**Comment by furey** [comment]
No worries! Thanks for your hard work.

**Comment by furey** [comment]
Hi @ooxif. Would it be possible to get a 1.0.3 release tagged?

**Comment by ooxif** [comment]
Hi @furey i've tagged 1.0.3!

**Comment by furey** [comment]
Legend! Cheers.

**Pull request merged**
